// <auto-generated />
using System;
using DevilTeam.Hera.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevilTeam.Hera.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DevilTeam.Hera.Platform.DevicesManagement.Domain.Model.Aggregates.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Connectivity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("connectivity");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsOn")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_on");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("room");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_devices");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("DevilTeam.Hera.Platform.DevicesManagement.Domain.Model.Aggregates.Device", b =>
                {
                    b.OwnsOne("DevilTeam.Hera.Platform.DevicesManagement.Domain.Model.ValueObjects.DeviceCode", "Code", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("code");

                            b1.HasKey("Id")
                                .HasName("p_k_devices");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_devices_devices_id");
                        });

                    b.OwnsOne("DevilTeam.Hera.Platform.DevicesManagement.Domain.Model.ValueObjects.DeviceName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_devices");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_devices_devices_id");
                        });

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
